-- MySQL Script generated by MySQL Workbench
-- Sat Nov 19 14:28:34 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema frost
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema frost
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `frost` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `frost` ;

-- -----------------------------------------------------
-- Table `frost`.`chest`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `frost`.`chest` (
  `id` BIGINT NOT NULL,
  `qnty` INT NOT NULL,
  `value` FLOAT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `frost`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `frost`.`user` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `contact` VARCHAR(255) NULL DEFAULT NULL,
  `email` VARCHAR(255) NULL DEFAULT NULL,
  `email_recover` VARCHAR(255) NULL DEFAULT NULL,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `password` VARCHAR(255) NULL DEFAULT NULL,
  `chest_id` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK4uax7ys35snwxpy0v45km8cxs` (`chest_id` ASC) VISIBLE,
  CONSTRAINT `FK4uax7ys35snwxpy0v45km8cxs`
    FOREIGN KEY (`chest_id`)
    REFERENCES `frost`.`chest` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `frost`.`buy`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `frost`.`buy` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FKkhggp13kai501c16q0o3xt1ap` (`user_id` ASC) VISIBLE,
  CONSTRAINT `FKkhggp13kai501c16q0o3xt1ap`
    FOREIGN KEY (`user_id`)
    REFERENCES `frost`.`user` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `frost`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `frost`.`product` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `price` FLOAT NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `frost`.`products_in_chest`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `frost`.`products_in_chest` (
  `chest_id` BIGINT NOT NULL,
  `products_id` BIGINT NOT NULL,
  INDEX `FKp4lxaeijamvruhvoeibaurbkr` (`products_id` ASC) VISIBLE,
  INDEX `FK1a1ne8gu4rj39h8hs4smdq11e` (`chest_id` ASC) VISIBLE,
  CONSTRAINT `FK1a1ne8gu4rj39h8hs4smdq11e`
    FOREIGN KEY (`chest_id`)
    REFERENCES `frost`.`chest` (`id`),
  CONSTRAINT `FKp4lxaeijamvruhvoeibaurbkr`
    FOREIGN KEY (`products_id`)
    REFERENCES `frost`.`product` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `frost`.`products_in_buys`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `frost`.`products_in_buys` (
  `buy_id` BIGINT NOT NULL,
  `products_id` BIGINT NOT NULL,
  INDEX `FKkcb7ocuqueceon2ygmjdlxcl` (`products_id` ASC) VISIBLE,
  INDEX `FKicjve504vwtfl2oqss2n983f9` (`buy_id` ASC) VISIBLE,
  CONSTRAINT `FKicjve504vwtfl2oqss2n983f9`
    FOREIGN KEY (`buy_id`)
    REFERENCES `frost`.`buy` (`id`),
  CONSTRAINT `FKkcb7ocuqueceon2ygmjdlxcl`
    FOREIGN KEY (`products_id`)
    REFERENCES `frost`.`product` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
